### PR TITLE
Hide Empty Dropdown

### PR DESCRIPTION
**Pull request by firstor**
The PR resolves the problem that the dropdown keeps opened while form input field gets changed though it has no items from observable.

#### `tag-input` usecase
```html
<tag-input class="tag-input"
           theme="my-custom-theme"
           identifyBy="name"
           displayBy="name"
           editable="false"
           maxItems="25"
           onlyFromAutocomplete="false"
           separatorKeys=" "
           ...>
    <tag-input-dropdown [autocompleteObservable]="requestTagItems"
                        showDropdownIfEmpty="false"
                        minimumTextLength="2"
                        appendToBody="false"
                        zIndex="9999"
                        identifyBy="name"
                        displayBy="name"
                        [matchingFn]="dropdownMatchFn">
    </tag-input-dropdown>
</tag-input>
```

#### Reproduction
* enter the valid candidate
    then dropdown gets opened with some autocomplete items
* next, input some backspaces to remove some characters, or input invalid candidate
    then observable returns no autocomplete item
* so the dropdown keep opened with empty menu

See also screenshot below:
image

#### Misc
* I also reviewed all commits related with `/modules/components/dropdown/tag-input-dropdown.component.ts` and found something strange: https://github.com/Gbuomprisco/ngx-chips/commit/25dd0565152ca0dea53036b9d4206da1a07a634a. Since `A OR AB => A` but duplicate case was made, so I fixed it.

### CODE REVIEW

**Comment by firstor** [comment]
@Gbuomprisco Build was done successfully. Hope to get your review and new release asap. Thanks.

**Comment by firstor** [comment]
@Gbuomprisco Could you review this PR? Thanks for the update in advance.

**Comment by firstor** [comment]
@Gbuomprisco Thank you for merging. Could you also let me know when you release new version?

**Comment by Gbuomprisco** [comment]
Hi the version is released

**Comment by firstor** [comment]
@Gbuomprisco Thanks.

**Pull request merged**
