### PR TITLE
Fixing problem with autocomplete list not showing recent removed item

### PR DESCRIPTION
**Pull request by DkArteid**
Fixing problem with autocomplete list not showing recent removed item
Changed so it doesn't show the list right after an item is removed or added
Added click event handler to open the dropdown list

### CODE REVIEW

**Comment by manu7691** [comment]
Hey guys, any idea when will this be merged? Thanks

**Comment by Gbuomprisco** [comment]
Not sure if it applies to the latest version, have you tried it?

**Comment by manu7691** [comment]
@Gbuomprisco As far as I know, the bug is still there, you can check it on the demo page. I'm not sure if this code breaks the actual one.

**Comment by Gbuomprisco** [comment]
The demo is outdated in case you only tried it there

**Comment by manu7691** [comment]
@Gbuomprisco It's still there, I just tried ngx-chips 1.4.6

**Comment by Gbuomprisco** [comment]
would you be able to describe what's expected? having a hard time understanding the description of this PR (as from what I understand the behaviour is correct)

**Comment by DkArteid** [comment]
Hey @Gbuomprisco, sorry for my poor english, what I meant in the description is if you remove a chip from the input when using autocomplete list, the popup list displays without that removed chip, in order to show the removed chip you need to close the dropdown list and open it again.
As for the click handler event, if the input is already focuses, clicking on it wont open the dropdown list, you need to move the focus elsewhere and back to get the list.
Please lemme know if you need more details.

**Pull request closed without merging**
