### PR TITLE
Add a pasteSplitRegex option, to enable more complex spilt operations on paste

### PR DESCRIPTION
**Pull request by yonicozac**

### CODE REVIEW

**Comment by Gbuomprisco** [comment]
Hi @yonicozac, thanks for the PR. I was thinking maybe we could just reuse pasteSplitPattern and have it as either a RegExp or a string? In which case we'd only need to add the typing.

**Comment by yonicozac** [comment]
Sure, i would love that, but i dont think it is possible to perform a bind to a regexp type, so the only way i found to make it work was binding it as string and creating a regexp object with that value. 
I couldnt ride on pasteSplitPattern because i cannot differentiate between the two values, they are both strings.. 

Admitedly i'm not that expirienced with Angular, so good chance i'm missing something.

Thanks for the reply!

**Comment by Gbuomprisco** [comment]
Hi @yonicozac, I am not sure why you had issues binding to a RegExp. I just tried and it seems to be OK. Did you get any errors or it just wasn't working?

When you call .split(pattern), it doesn't really matter whether pattern is a String or RegExp, so we should be safe.

**Comment by Gbuomprisco** [comment]
But that's totally expected :) it's up to the user to provide the correct string or the correct regexp :)

**Comment by yonicozac** [comment]
But as i said, i couldn't manage to bind to RegExp, so the user can only supply strings. How did you manage to bind a RegExp?

**Comment by Gbuomprisco** [comment]
You pass it like any other object. As far as I know there's no limitation to what you can pass down to inputs

**Comment by yonicozac** [comment]
If i'm trying `[pasteSplitPattern]="/;|,/"`, i'm getting a "Template parse error - Unexpected token /", if i'm trying to escape the '/' -  `[pasteSplitPattern]="//;|,//"`, then my value is ignored and I get the default value. As I said, good chance that i'm missing something basic..

**Comment by Gbuomprisco** [comment]
It's likely that the templating system won't bind the regexp for you, but try to assign it as a property instead. Not only it does work, it's also the right way :)

**Comment by yonicozac** [comment]
You're right. I was fighting to bind via the template just to show an easy example in the readme. I'll do a separate pull request only for the typing changes

**Comment by agiratech-vigneshm** [comment]
I can't find any example for binding a regex, Is there anything available in the docs? I tried from the component and by binding the variable into html, but I couldn't make it work.

**Comment by Gbuomprisco** [comment]
Do you get errors?

**Comment by agiratech-vigneshm** [comment]
Sorry, it was my bad, I forgot the [ ] square brackets around pasteSplitPattern so instead of Actual regex the component was receiving the variable name as a string, I debugged it and corrected the mistake. 

This is really a great project, Kudos to your work, I will update the docs with some examples using regex and any other advanced examples (it'll be easy). Thanks for your work and support once again.

**Comment by g3344** [comment]
Hi, great project.  How regex for pasteSplitPattern does this work?  

If I want a split patter to use , or ; or | ...do I use [pasteSplitPattern]="[,|;]" ?

That seems to show an error for me of "Parser Error: Unexpected token ,"

**Pull request closed without merging**
