### PR TITLE
fix(aot): make the library work with aot

### PR DESCRIPTION
**Pull request by mattlewis92**
Same changes as the ones I made over at `ng2-material-dropdown`, tested with AoT on our app and everything works smoothly 😄 

I also had to tweak the exports slightly because of https://github.com/angular/angular-cli/issues/1831#issuecomment-242401992

I also fixed html code coverage reporting while I was there

### CODE REVIEW

**Comment by mattlewis92** [comment]
Awesome, thanks @Gbuomprisco. Any chance you could give me npm access as well or publish 1.6.0 to npm? 😄

**Comment by Gbuomprisco** [comment]
just published 1.6.0 :) will add you to npm soon!

**Comment by mattlewis92** [comment]
Thanks! It looks like you've published the wrong folder to npm though (if you do `npm run release` it should handle everything)

**Comment by Gbuomprisco** [comment]
right, totally forgot about that! Never release after drinks! :)

**Pull request merged**
