### PR TITLE
Update to Angular 6

### PR DESCRIPTION
**Pull request by alippai**

### CODE REVIEW

**Comment by Gbuomprisco** [comment]
Hi @alippai, thanks a lot for the PR. The checks have failed, likely the tests are using something deprecated

**Comment by alippai** [comment]
I see. :(
I couldn't manage to set up the tests locally, so this was a blind PR.
I hope it helps at least.

**Comment by Gbuomprisco** [comment]
Hi @alippai, I pulled your branch and updated the tests in a different branch, the PR is https://github.com/Gbuomprisco/ngx-chips/pull/750. You contributions will appear there :) Thanks

**Comment by alippai** [comment]
Nice, thank you!

**Pull request closed without merging**
