### PR TITLE
fix for an issue: Adding new Tag with autocomplete #437

### PR DESCRIPTION
**Pull request by magarbikram**
this issue seems to be fixed: https://github.com/Gbuomprisco/ng2-tag-input/issues/437

I have pushed to master, as the version is not updated in develop branch

### CODE REVIEW

**Comment by eyalhakim** [comment]
@Gbuomprisco Please merge this, it fixes an issue i am also experiencing.

Thank you

**Comment by Gbuomprisco** [comment]
@eyalhakim the build failed, can't merge

**Comment by eyalhakim** [comment]
@magarbikram, @Gbuomprisco  i tried taking a quick look but couldn't understand why this test fails:
TagInputComponent testing validators validates transformed values

Can one of you maybe get to the bottom of this?

Thanks

**Comment by Gbuomprisco** [comment]
@eyalhakim I'll try take a look tomorrow

**Comment by eyalhakim** [comment]
@Gbuomprisco Hey there, sorry to bug you but we are highly dependent on your library. Any updates regarding this?

**Comment by magarbikram** [comment]
I believe, you can change the source code .js/.ts and then it will work perfectly, that's what I am doing right now. I am not sure why build failed, I just did change one line and then commit.

**Comment by Gbuomprisco** [comment]
@eyalhakim @magarbikram the test caught a bug: by passing item, the transform function would not work

**Comment by eyalhakim** [comment]
@magarbikram @Gbuomprisco any idea how to fix?

**Comment by Gbuomprisco** [comment]
not yet, I can't reproduce the issue

**Comment by eyalhakim** [comment]
@Gbuomprisco i can help, how can i contact you?

**Pull request closed without merging**
